# Site
name: "Thousandfeeds"
title: "Thousandfeeds"
description: "Entities from different dimensions."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: 'UA-64548998-1'
disqus: 'thousandfeeds'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  barun:
    name: Barun
    display_name: Barun Kalita
    avatar: 'assets/images/barun.jpg'
    email: barunkalita1993@gmail.com
    web: https://www.facebook.com/barun.kalita.3
    Linkedin: https://www.linkedin.com/in/barun-kalita-3a8809a2/
    description: "Interested in technology, culture, politics, sports, history etc."
  parag:
    name: Parag Jyoti Nath
    display_name: Parag Jyoti Nath
    gravatar: 5eba783a90884332b80820d154e52aec
    email: paragjnath@gmail.com
    web: https://www.linkedin.com/in/paragjyoti/
    twitter: https://twitter.com/paragjnath
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."
  thousandfeeds:
    name: Thousandfeeds
    display_name: Thousandfeeds
    avatar: 'assets/images/logo.png'
    email: thousanfeeds@gmail.com
    web: https://thousandfeeds.com
    twitter: https://twitter.com/thousandfeeds
    description: 'This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages.'
    web: https://thousandfeeds.com
    twitter: https://twitter.com/paragjnath
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "enabled"
adsense-data-ad-client: "ca-pub-8026145480801361"
adsense-data-ad-slot: "4251932288"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
